export const categories = [
  {
    id: "1",
    name: "Running",
    billboard: { id: "b1", label: "Run Faster", imageUrl: "/images/image-1.jpg" },
  },
  {
    id: "2",
    name: "Basketball",
    billboard: { id: "b2", label: "Jump Higher", imageUrl: "/images/image-2.jpg" },
  },
  {
    id: "3",
    name: "Training",
    billboard: { id: "b3", label: "Train Harder", imageUrl: "/images/shoe-3.jpg" },
  },
  {
    id: "4",
    name: "Lifestyle",
    billboard: { id: "b4", label: "Live Bold", imageUrl: "/images/shoe-4.jpg" },
  },
  {
    id: "5",
    name: "Womens",
    billboard: { id: "b5", label: "For Her", imageUrl: "/images/r-n-tyfqOL1FAQc-unsplash.jpg" },
  },
  {
    id: "6",
    name: "Watches",
    billboard: { id: "b6", label: "Timeless", imageUrl: "/images/shahrukh-rehman-05IxAEjVNl0-unsplash.jpg" },
  },
  {
    id: "7",
    name: "Phones",
    billboard: { id: "b7", label: "Stay Connected", imageUrl: "/images/aaditya-ailawadhi-D6pgxi3gwNQ-unsplash.jpg" },
  },
  {
    id: "8",
    name: "Mens Wear",
    billboard: { id: "b8", label: "For Him", imageUrl: "/images/moses-janga-WZaPKRy4zYQ-unsplash.jpg" },
  },
];

export const sizes = [
  { id: "s1", name: "S", value: "S" },
  { id: "s2", name: "M", value: "M" },
  { id: "s3", name: "L", value: "L" },
  { id: "s4", name: "XL", value: "XL" },
];

export const colors = [
  { id: "c1", name: "Black", value: "#000" },
  { id: "c2", name: "White", value: "#fff" },
  { id: "c3", name: "Red", value: "#f00" },
  { id: "c4", name: "Blue", value: "#00f" },
];

export const products = [
  {
    id: "p1",
    name: "React Runner",
    description: "Fast and light",
    price: "129.99",
    category: categories[0],
    size: sizes[1],
    color: colors[0],
    images: [
      { id: "i1", url: "/images/shoe-1.jpg" },
      { id: "i1b", url: "/images/image-1.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p2",
    name: "Court Pro",
    description: "Built for the court",
    price: "149.99",
    category: categories[1],
    size: sizes[2],
    color: colors[1],
    images: [
      { id: "i2", url: "/images/shoe-2.jpg" },
      { id: "i2b", url: "/images/image-2.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p3",
    name: "Gym Flex",
    description: "Stable support",
    price: "109.99",
    category: categories[2],
    size: sizes[0],
    color: colors[2],
    images: [
      { id: "i3", url: "/images/shoe-3.jpg" },
      { id: "i3b", url: "/images/image-1.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p4",
    name: "Street Classic",
    description: "Everyday comfort",
    price: "99.99",
    category: categories[3],
    size: sizes[3],
    color: colors[3],
    images: [
      { id: "i4", url: "/images/shoe-4.jpg" },
      { id: "i4b", url: "/images/nike-just-do-it.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p5",
    name: "Trail Blazer",
    description: "Rugged traction",
    price: "139.99",
    category: categories[0],
    size: sizes[2],
    color: colors[2],
    images: [
      { id: "i5", url: "/images/shoe-5.jpg" },
      { id: "i5b", url: "/images/graph-paper.svg" },
    ],
    isFeatured: false,
  },
  {
    id: "p6",
    name: "Trail Runner",
    description: "Tackles rough terrain",
    price: "159.99",
    category: categories[0],
    size: sizes[2],
    color: colors[1],
    images: [
      { id: "i6", url: "/images/shoe-6.jpg" },
      { id: "i6b", url: "/images/shoe-1.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p7",
    name: "City Slip",
    description: "Comfortable everyday shoe",
    price: "89.99",
    category: categories[3],
    size: sizes[0],
    color: colors[3],
    images: [
      { id: "i7", url: "/images/shoe-5.jpg" },
      { id: "i7b", url: "/images/shoe-2.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p8",
    name: "Dash Sprint",
    description: "Lightweight running shoe",
    price: "139.99",
    category: categories[0],
    size: sizes[1],
    color: colors[1],
    images: [
      { id: "i8", url: "/images/shoe-7.jpg" },
      { id: "i8b", url: "/images/shoe-6.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p9",
    name: "Endurance Pro",
    description: "Long-distance comfort",
    price: "149.99",
    category: categories[0],
    size: sizes[2],
    color: colors[0],
    images: [
      { id: "i9", url: "/images/shoe-6.jpg" },
      { id: "i9b", url: "/images/shoe-7.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p10",
    name: "Hoop Master",
    description: "Professional court shoe",
    price: "169.99",
    category: categories[1],
    size: sizes[2],
    color: colors[3],
    images: [
      { id: "i10", url: "/images/shoe-5.jpg" },
      { id: "i10b", url: "/images/shoe-6.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p11",
    name: "Court Lite",
    description: "Light and responsive",
    price: "119.99",
    category: categories[1],
    size: sizes[1],
    color: colors[2],
    images: [
      { id: "i11", url: "/images/shoe-5.jpg" },
      { id: "i11b", url: "/images/shoe-6.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p13",
    name: "Orbit Runner",
    description: "Daily trainer with great traction",
    price: "129.99",
    category: categories[0],
    size: sizes[1],
    color: colors[1],
    images: [
      { id: "i13", url: "/images/shoe-4.jpg" },
      { id: "i13b", url: "/images/shoe-5.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p14",
    name: "Sky Dunk",
    description: "High-top with superior ankle support",
    price: "179.99",
    category: categories[1],
    size: sizes[3],
    color: colors[3],
    images: [
      { id: "i14", url: "/images/shoe-6.jpg" },
      { id: "i14b", url: "/images/shoe-5.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p15",
    name: "Courtside Pro",
    description: "Engineered for quick cuts on court",
    price: "139.99",
    category: categories[1],
    size: sizes[2],
    color: colors[2],
    images: [
      { id: "i15", url: "/images/shoe-5.jpg" },
      { id: "i15b", url: "/images/shoe-6.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p16",
    name: "Sheer Comfort",
    description: "Designed for women",
    price: "129.99",
    category: categories[4],
    size: sizes[1],
    color: colors[1],
    images: [
      { id: "i16", url: "/images/r-n-tyfqOL1FAQc-unsplash.jpg" },
      { id: "i16b", url: "/images/r-n-tyfqOL1FAQc-unsplash.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p17",
    name: "Womens Runner",
    description: "Run in style",
    price: "139.99",
    category: categories[4],
    size: sizes[2],
    color: colors[0],
    images: [
      { id: "i17", url: "/images/r-n-tyfqOL1FAQc-unsplash.jpg" },
      { id: "i17b", url: "/images/shoe-1.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p18",
    name: "Nikhil Slip",
    description: "Comfort meets design",
    price: "119.99",
    category: categories[4],
    size: sizes[1],
    color: colors[0],
    images: [
      { id: "i18", url: "/images/nikhil-uttam-QrOdhsMAQw8-unsplash.jpg" },
      { id: "i18b", url: "/images/nikhil-uttam-QrOdhsMAQw8-unsplash.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p19",
    name: "Raquel Slip",
    description: "Comfort meets design",
    price: "150.99",
    category: categories[4],
    size: sizes[1],
    color: colors[0],
    images: [
      { id: "i19", url: "/images/raquel-gambin-kS3YkVtf85U-unsplash (1).jpg" },
      { id: "i19b", url: "/images/raquel-gambin-kS3YkVtf85U-unsplash (1).jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p20",
    name: "Shahrukh Watch Classic",
    description: "Elegant timepiece inspired by Shahrukh",
    price: "199.99",
    category: categories[5],
    size: sizes[1],
    color: colors[0],
    images: [
      { id: "i20", url: "/images/shahrukh-rehman-05IxAEjVNl0-unsplash.jpg" },
      { id: "i20b", url: "/images/shahrukh-rehman-05IxAEjVNl0-unsplash.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p21",
    name: "Shahrukh Sport Watch",
    description: "Sporty and reliable",
    price: "179.99",
    category: categories[5],
    size: sizes[2],
    color: colors[3],
    images: [
      { id: "i21", url: "/images/shahrukh-rehman-05IxAEjVNl0-unsplash.jpg" },
      { id: "i21b", url: "/images/shahrukh-rehman-05IxAEjVNl0-unsplash.jpg" },
    ],
    isFeatured: false,
  },
   {
    id: "p22",
    name: "Rolex S Watch",
    description: "Sporty and reliable",
    price: "2000.99",
    category: categories[5],
    size: sizes[2],
    color: colors[3],
    images: [
      { id: "i22", url: "/images/yash-parashar-LWPPpkn6NEQ-unsplash.jpg" },
      { id: "i22b", url: "/images/yash-parashar-LWPPpkn6NEQ-unsplash.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p23",
    name: "Aaditya Phone One",
    description: "Sleek smartphone inspired by Aaditya",
    price: "499.99",
    category: categories[6],
    size: sizes[1],
    color: colors[0],
    images: [
      { id: "i23", url: "/images/aaditya-ailawadhi-D6pgxi3gwNQ-unsplash.jpg" },
      { id: "i23b", url: "/images/aaditya-ailawadhi-D6pgxi3gwNQ-unsplash.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p24",
    name: "Aaditya Phone Mini",
    description: "Compact and powerful",
    price: "399.99",
    category: categories[6],
    size: sizes[0],
    color: colors[1],
    images: [
      { id: "i24", url: "/images/d-c-tr-nh-1t1CBECuqvs-unsplash.jpg" },
      { id: "i24b", url: "/images/d-c-tr-nh-1t1CBECuqvs-unsplash.jpg"},
    ],
    isFeatured: false,
  },
  {
    id: "p25",
    name: "Moses Classic",
    description: "Timeless menswear piece",
    price: "159.99",
    category: categories[7],
    size: sizes[2],
    color: colors[0],
    images: [
      { id: "i25", url: "/images/moses-janga-WZaPKRy4zYQ-unsplash.jpg" },
      { id: "i25b", url: "/images/moses-janga-WZaPKRy4zYQ-unsplash.jpg" },
    ],
    isFeatured: true,
  },
  {
    id: "p26",
    name: "Moses Casual",
    description: "Everyday menswear",
    price: "129.99",
    category: categories[7],
    size: sizes[1],
    color: colors[1],
    images: [
      { id: "i26", url: "/images/moses-janga-WZaPKRy4zYQ-unsplash.jpg" },
      { id: "i26b", url: "/images/moses-janga-WZaPKRy4zYQ-unsplash.jpg" },
    ],
    isFeatured: false,
  },
  {
    id: "p27",
    name: "Bruno Jacket",
    description: "Sharp mens jacket by Bruno Cervera",
    price: "189.99",
    category: categories[7],
    size: sizes[2],
    color: colors[0],
    images: [
      { id: "i27", url: "/images/bruno-cervera-71HxayOVDfI-unsplash.jpg" },
      { id: "i27b", url: "/images/bruno-cervera-71HxayOVDfI-unsplash.jpg" },
    ],
    isFeatured: false,
  },
];

export const reviews = [];
